FROM arm32v7/python:3.7-slim
COPY --from=multiarch/qemu-user-static:x86_64-arm /usr/bin/qemu-* /usr/bin

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

RUN mkdir /app
WORKDIR /app

COPY powermon powermon

ENTRYPOINT ["python", "-u", "-m", "powermon.telemd"]
